ALTER TABLE users ADD COLUMN yearly_commits INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN monthly_commits INT NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN weekly_commits INT NOT NULL DEFAULT 0;
